// <auto-generated />
using iDecorate.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace iDecorate.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20170921035524_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");
                //.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("iDecorate.Data.Entity.TopicEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<Guid>("id_user");

                    b.HasKey("id");

                    b.ToTable("topic");
                });

            modelBuilder.Entity("iDecorate.Data.Entity.WordEntity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<Guid>("id_product");

                    b.Property<string>("meaning");

                    b.Property<Guid?>("topicid");

                    b.HasKey("id");

                    b.HasIndex("topicid");

                    b.ToTable("word");
                });

            modelBuilder.Entity("iDecorate.Data.Entity.WordEntity", b =>
                {
                    b.HasOne("iDecorate.Data.Entity.TopicEntity", "topic")
                        .WithMany("words")
                        .HasForeignKey("topicid");
                });
#pragma warning restore 612, 618
        }
    }
}
